import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import Handlebars from 'handlebars';
import type { DomainAnalysis, TeamProposal } from '../types.js';

// Resolve templates directory relative to this module
const templatesDir = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'templates');

// Fallback inline templates (used when .hbs files unavailable)
const DEV_AGENT_FALLBACK = `---
description: {{description}}
mode: subagent
tools:
  write: true
  edit: true
  bash: true
  read: true
  glob: true
  grep: true
permission:
  edit:
{{#each permissions}}
    "{{@key}}": "{{this}}"
{{/each}}
---

{{promptContent}}`;

const REVIEWER_FALLBACK = `---
description: Code reviewer for {{projectName}}. Forensic auditor. Read-only.
mode: subagent
temperature: 0.1
tools:
  write: false
  edit: false
  bash: true
  read: true
  glob: true
  grep: true
permission:
  edit:
    "*": "deny"
  bash:
    "*": "allow"
---

You are the {{projectName}} code reviewer. Every finding cites file:line.

## Verdict
PASSED / FIX REQUIRED / BLOCKED

## Review Checklist
### CRASH-LEVEL — unbound variables, type mismatches, uncaught exceptions, missing await
{{#each knownBugs}}- {{this}}
{{/each}}

### DATA FLOW — dict key mismatches, wrong data structure access, relative paths
### ARCHITECTURE — single responsibility, no hidden coupling, no hardcoded secrets

## Severity
CRASH > HIGH > MEDIUM > LOW

## Known Bug Patterns
{{#if knownPatterns}}{{knownPatterns}}{{else}}_None yet. Grows as bugs are discovered._{{/if}}

## Report Format
\`\`\`
## VERDICT: PASSED / FIX REQUIRED / BLOCKED
### CRASH (X found)
| File:Line | Mechanism | Fix |
### Summary
\`\`\``;

async function loadTemplate(name: string, fallback: string): Promise<string> {
  try {
    return await readFile(join(templatesDir, name), 'utf-8');
  } catch {
    return fallback;
  }
}

export async function generateAgents(
  dir: string,
  analyses: DomainAnalysis[],
  projectName: string
): Promise<string[]> {
  const promptsDir = join(dir, 'prompts');
  await mkdir(promptsDir, { recursive: true });

  const templateStr = await loadTemplate('dev-agent.hbs', DEV_AGENT_FALLBACK);
  const compile = Handlebars.compile(templateStr);
  const paths: string[] = [];

  for (const analysis of analyses) {
    if (!analysis.promptContent) continue;

    const content = compile({
      description: `${analysis.agentName} agent for ${projectName}. Owns ${analysis.domain.fileCount} files.`,
      permissions: analysis.permissions.allow,
      promptContent: analysis.promptContent,
    });

    const filename = `${analysis.agentName}.md`;
    const filePath = join(promptsDir, filename);
    await writeFile(filePath, content, 'utf-8');
    paths.push(filePath);
  }

  return paths;
}

export async function generateReviewer(
  dir: string,
  projectName: string,
  knownBugs: string[],
  knownPatterns: string
): Promise<string> {
  const promptsDir = join(dir, 'prompts');
  const templateStr = await loadTemplate('reviewer-agent.hbs', REVIEWER_FALLBACK);
  const compile = Handlebars.compile(templateStr);

  const content = compile({
    projectName,
    knownBugs,
    knownPatterns,
  });

  const filePath = join(promptsDir, 'reviewer.md');
  await writeFile(filePath, content, 'utf-8');
  return filePath;
}

export async function generateProjectContext(
  dir: string,
  proposal: TeamProposal,
  survey: { name: string; language: string; framework?: string; packageManager: string }
): Promise<string> {
  const templateStr = await loadTemplate('project-context.hbs', '');
  let content: string;

  if (templateStr && templateStr.length > 10) {
    const compile = Handlebars.compile(templateStr);
    content = compile({
      name: survey.name,
      date: new Date().toISOString().split('T')[0],
      narrative: proposal.narrative,
      language: survey.language,
      framework: survey.framework,
      packageManager: survey.packageManager,
      agents: proposal.agents.map((a, i) => ({
        index_1: i + 1,
        agentName: a.domainAnalysis.agentName,
        domain: a.domainAnalysis.domain,
        temperature: a.domainAnalysis.temperature,
        qualityReport: a.domainAnalysis.qualityReport,
      })),
      warnings: proposal.warnings,
    });
  } else {
    content = `# ${survey.name} — Project Context

> Generated by Genesis · ${new Date().toISOString().split('T')[0]}

## Overview

${proposal.narrative}

## Architecture

${survey.name} is built with ${survey.language}${survey.framework ? ` (${survey.framework})` : ''}.
Package manager: ${survey.packageManager}.

## Agent Team

${proposal.agents.map((a, i) => {
  const da = a.domainAnalysis;
  return `### ${i + 1}. ${da.agentName}
**Domain**: ${da.domain.paths.join(', ')} (${da.domain.fileCount} files)
**Temperature**: ${da.temperature}

**Quality Report**:
${da.qualityReport.bugs.length > 0 ? `- 🐛 ${da.qualityReport.bugs.length} bugs found` : ''}
${da.qualityReport.securityIssues.length > 0 ? `- 🔒 ${da.qualityReport.securityIssues.length} security issues` : ''}
${da.qualityReport.aiSlopConfirmed.length > 0 ? `- 🤖 ${da.qualityReport.aiSlopConfirmed.length} AI slop patterns` : ''}
${da.qualityReport.testGaps.length > 0 ? `- 🧪 ${da.qualityReport.testGaps.length} test gaps` : ''}
${da.qualityReport.summary ? `\n${da.qualityReport.summary}` : ''}
`;
}).join('\n')}

## Warnings

${proposal.warnings.length > 0 ? proposal.warnings.map((w) => `- ⚠️ ${w}`).join('\n') : 'None'}

## How to Use

1. Read each agent's prompt file in \`./prompts/\`
2. Switch to the appropriate agent for your task
3. The reviewer gates all changes before merge

---

*Generated by Genesis — \`npx genesis .\`*
`;
  }

  const filePath = join(dir, 'PROJECT-CONTEXT.md');
  await writeFile(filePath, content, 'utf-8');
  return filePath;
}
